"""Backward-compatibility re-export shim.

The monolithic core type module was split by concern.  Type surface now lives
in per-package ``types.py`` modules; this shim re-exports the symbols from
their new homes so internal importers keep working for one release.  Provider
model TypeVars and ``ModelBase`` are **not** re-exported: they were removed
from the public core surface (provider type parameters now live in
:mod:`pyverge.providers.types`).
"""

from __future__ import annotations

from pyverge.core.types import (
    MIGRATION_PAIR_LEN,
    Attachable,
    Comparable,
    Diffable,
    DirectionViolationStrategy,
    ExtraFieldStrategy,
    JsonPrimities,
    JsonSchema,
    JsonSchemaDefinitions,
    JsonSchemaGenerator,
    JsonSchemaMode,
    JsonValue,
    LookupKey,
    ManagerKey,
    ManagerMigrationKey,
    Migratable,
    MigrationDirectionStrategy,
    MigrationFunc,
    MigrationHookMap,
    MigrationKey,
    MigrationKeyInput,
    MissingFieldStrategy,
    ModelData,
    ModelHandle,
    ModelKey,
    ModelKind,
    ModelPair,
    ModelVersionKey,
    Orderable,
    Renderable,
    RenderingFormat,
    SchemaTransformer,
    TargetResolver,
    TargetStrategy,
    Transitional,
    ValidationMode,
    Versionable,
    VersionMissingStrategy,
    VersionPair,
    VersionValue,
    VersionValue_co,
)
from pyverge.core.versioning import (
    SentinelEdge,
    VersionEdge,
    VersionNode,
)
from pyverge.manager.types import (
    ManagerClassState,
    ManagerInstanceState,
    ResolverFactory,
    TargetPolicy,
    TargetSpec,
)
from pyverge.migration.types import (
    Entry,
    Executor,
    MigrationEntry,
    RunnableMigration,
    Walker,
)
from pyverge.providers.types import (
    ModelAdapter,
)

__all__ = [
    "MIGRATION_PAIR_LEN",
    "Attachable",
    "Comparable",
    "Diffable",
    "DirectionViolationStrategy",
    "Entry",
    "Executor",
    "ExtraFieldStrategy",
    "JsonPrimities",
    "JsonSchema",
    "JsonSchemaDefinitions",
    "JsonSchemaGenerator",
    "JsonSchemaMode",
    "JsonValue",
    "LookupKey",
    "ManagerClassState",
    "ManagerInstanceState",
    "ManagerKey",
    "ManagerMigrationKey",
    "Migratable",
    "MigrationDirectionStrategy",
    "MigrationEntry",
    "MigrationFunc",
    "MigrationHookMap",
    "MigrationKey",
    "MigrationKeyInput",
    "MissingFieldStrategy",
    "ModelAdapter",
    "ModelData",
    "ModelHandle",
    "ModelKey",
    "ModelKind",
    "ModelPair",
    "ModelVersionKey",
    "Orderable",
    "Renderable",
    "RenderingFormat",
    "ResolverFactory",
    "RunnableMigration",
    "SchemaTransformer",
    "SentinelEdge",
    "TargetPolicy",
    "TargetResolver",
    "TargetSpec",
    "TargetStrategy",
    "Transitional",
    "ValidationMode",
    "VersionEdge",
    "VersionMissingStrategy",
    "VersionNode",
    "VersionPair",
    "VersionValue",
    "VersionValue_co",
    "Versionable",
    "Walker",
]
