name: Publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  UV_FROZEN: "1"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.11"
      - run: uv sync --group dev --all-extras
      - run: uv run hatch build
      - name: Publish to GitHub Packages
        run: |
          uv publish \
            --index-url https://maven.pkg.github.com/${{ github.repository }} \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }}
